#!/bin/bash

if [ -t 1 ] ; then
    HEADER_START="$(tput bold)$(tput setaf 8)"
    HEADER_END="$(tput sgr0)"
else
    HEADER_START=""
    HEADER_END=""
fi

function header {
    echo -n "$HEADER_START"
    echo "============================================================"
    echo "$@"
    echo "============================================================"
    echo -n "$HEADER_END"
}

out=$(mktemp)
err=$(mktemp)

while read repo; do
    git -C $repo "$@" > $out 2> $err
    if [ -s $out -o -s $err ]; then
        header $repo
        cat $out $err
    fi
done < <(find . -name .git -type d -exec dirname {} \;)
