require("core/options")
require("core/keymap")
require("plugins/oil-bundle")
require("plugins/fzf-bundle")
require("plugins/gruvbox-bundle")
require("plugins/vim-fugitive-bundle")
require("plugins/lsp-bundle")
